#!/usr/bin/env bash
# Install nginx server on an ubuntu server

# Update the package list and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

echo 'Hello World!' | sudo tee /var/www/html/index.html

# Restart the Nginx service to apply changes
sudo service nginx restart
