#!/usr/bin/env bash
# Configures Nginx server on an ubuntu server so that /redirect_me
# is redirecting to another page.

sudo apt-get -y update
sudo apt-get -y install nginx

echo 'Hello World!' | sudo tee /var/www/html/index.html
replacement_string="server_name _;\n\n\tlocation /redirect_me {\n\t\t return 301 https://www.veekode.tech;\n\t}\n"

sudo sed -i "s#server_name _;#$replacement_string#" /etc/nginx/sites-available/default

sudo service nginx restart
