#!/usr/bin/env bash
# Loops from 1 - 10 and display texts upon certain iterations

i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ];
	then
		echo "bad luck"
	elif [ $i -eq 8 ];
	then
		echo "goodluck"
	else
		echo "Best School"
	fi
	i=$(( i+1 ))
done
