#!/usr/bin/env bash
# Lists the content of the current directory

# Loop over each file in the current directory
for file in *;
do
	# Ignore hidden files
	if [[ $file != .* ]]; then
		# Extract the part of the name after the first dash
		name=$(echo "$file" | cut -d'-' -f2-)
		echo "$name"
	fi
done
