#!/usr/bin/env bash
# Configures an Ubuntu server
#	- localhost resolves to 127.0.0.2
#	- facebook.com resolves to 8.8.8.8

# Backup the hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Get the current IP address mapped to localhost
existing_ip=$(grep -oP '(?<=^127\.0\.0\.1[[:space:]]*)[^[:space:]]+' /etc/hosts)


#sudo sed -i 's/^127\.0\.0\.1\s*localhost/127\.0\.0\.2\tlocalhost/' /etc/hosts

sudo sed -i "/^127\\.0\\.0\\.1[[:space:]]*${existing_ip}$/d" /etc/hosts
echo "127.0.0.2	localhost" | sudo tee -a /etc/hosts > /dev/null
echo "8.8.8.8	facebook.com" | sudo tee -a /etc/hosts >> /dev/null
