#!/usr/bin/env bash
# Configures a container so that Nginx is running as the nginx user


# Stop nginx service if its running
service nginx stop

# Change nginx user to nginx
sed -i 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf

# Configure nginx to listen on port 8080 on all active IPs
sed -i 's/listen\s*80/listen 8080/g' /etc/nginx/sites-available/default
sed -i 's/listen\s*\[::\]:80/listen [::]:8080/g' /etc/nginx/sites-available/default

# set file permission to read but not write
chmod 644 /etc/nginx/nginx.conf

# kill any running instance of apache
pkill apache2

# Restart nginx service
sudo -u nginx service nginx start
